### ISSUE TITLE
Is the keytheorems package compatible with the tagging project?

### ISSUE THREAD

**Issue by FrankMittelbach** [mbertucci47/keytheorems#4]
Hi Matthew. In addition to being interested in the answer, I wanted to use this issue to ask you if you could contact me via email or some other direct communication channel. Addresses would be here: https://www.latex-project.org/about/team/

**Comment by mbertucci47** [comment]
> Is the keytheorems package compatible with the tagging project?

As it's just a wrapper around amsthm, no :-)

I could try to make it work in a limited way with the kernel `\newtheorem` like thmtools does, however since it currently has a user base of exactly one that doesn't seem pressing.

I'll reach out via email.

**Comment by mbertucci47** [comment]
@FrankMittelbach My university's mail server says the email was delayed. If you don't end up receiving it let me know and I'll try from a different email.

**Comment by FrankMittelbach** [comment]
@mbertucci47 not sure what the cause was (or is) ---  we moved the latex-project server and not everythiig is quite right yet ... but the mail reached me.

As to the package here: if it is a wrapper to amsthm, I guess in the end it will become automaticaly compatble once we fix amsthm itself.  So no real reason to keep this issue open.

**Comment by mbertucci47** [comment]
Tagging compatibility added in [v0.1.8](https://github.com/mbertucci47/keytheorems/releases/tag/v0.1.8) to go with amsthm compatibility added in the kernel. Everything except the `tcolorbox` features should work
