### ISSUE TITLE
Add commands to define theorem environments

### ISSUE THREAD

**Issue by texno3** [mbertucci47/keytheorems#5]
Thank you for making this powerful macro package of custom theorems. In some cases, it may be necessary to redefine or force define the theorem environment. Can you add `\renewkeytheorem`, `\providekeytheorem` and `\declarekeytheorem` three commands? If you make these commands, I think need to pay attention to cancel the definition of the existing environment, cancel the definition of the counter and binding relationships.

**Comment by mbertucci47** [comment]
@texno3 Thanks for your interest in the package. These commands should be available in the next release, though there are some technical issues with hooks I've not yet figured out

**Comment by mbertucci47** [comment]
Added in a4f335344111f0d683671c114c070aad979554f2. Will close this once the code is pushed to CTAN with a new version

**Comment by texno3** [comment]
> Added in [a4f3353](https://github.com/mbertucci47/keytheorems/commit/a4f335344111f0d683671c114c070aad979554f2). Will close this once the code is pushed to CTAN with a new version

You do not seem to consider the binding relationship of counters, such as the following example, first define the theorem number to follow the `chapter` counter, redefine the `section` counter, then the theorem number should not be reset when the chapter counter is increased, That is, the theorem numbers in Chapter 2 should be 2.2.2 and 2.2.3 instead of 2.2.1 and 2.2.2. Therefore, it is also necessary to unbind the `theorem `counter from the `chapter` counter when redefining the theorem.

```
\documentclass{book}

\counterwithout*{section}{chapter}
\usepackage{keytheorems,lipsum}
\newkeytheorem{theorem}[
name=Theorem, parent=chapter
]
\renewkeytheorem{theorem}[
name=Theorem, parent=section
]

\begin{document}

\chapter{TEST}
\section{TESTSEC}
\begin{theorem}
\lipsum[1]
\end{theorem}
\section{TESTSEC}
\begin{theorem}
\lipsum[1]
\end{theorem}

\chapter{TEST}
\begin{theorem}
\lipsum[1]
\end{theorem}
\begin{theorem}
\lipsum[1]
\end{theorem}

\end{document}
```

**Comment by mbertucci47** [comment]
You're right, thanks for the testing. I will look into how to fix this

**Comment by mbertucci47** [comment]
This is a little tricky because the data is stored in `\cl@<parent counter>`, so when you call `\renewkeytheorem` you have to know the value of `parent` previously called. The only way I can imagine doing this is globally storing the value of `parent` attached to each theorem

**Comment by texno3** [comment]
You only need to consider the counters bound to the theorem counters when you create a theorem environment with keytheorems, which is fully controllable, this can be done by logging the bound counters when you create a new theorem environment, and checking for the existence of bound counters when you redefine the theorem to decide whether or not to unbind the relationship.

such as When defining the theorem environment

```
parent.code:n = 
\keythms_thmstyle_savethmkey_reqval:n { #1 }
\tl_set:cn {l__keythms_parent_counter_\l__keythms_thm_envname_tl _tl}{#1},
```
When the theorem environment needs to be redefined

```
\tl_if_empty:cF {l__keythms_parent_counter_\l__keythms_thm_envname_tl _tl}
  {
    \exp_args:NNox
    \counterwithout*{\l__keythms_thm_envname_tl_tl}{\l__keythms_parent_counter_\l__keythms_thm_envname_tl_tl}
  }
```

**Comment by mbertucci47** [comment]
@texno3 Try with the recent commit

**Comment by texno3** [comment]
> @texno3 Try with the recent commit

When the theorem environment needs to be redefined, redefine the `\__keythms_thm_new_parent:nnn` command

\cs_set_protected:Npn \__keythms_thm_new_parent:nnn #1#2#3
  { 
    \__keythms_thm_new:w { #1 } { #2 } [ #3 ] 
    \tl_if_empty:NF\l__keythms_thm_parent_tl
      {
        \exp_args:NNVV
        \counterwithout*
        \l__keythms_thm_envname_tl \l__keythms_thm_parent_tl
      }
  }

**Comment by mbertucci47** [comment]
@texno3 That doesn't seem right. It would remove `\l__keythms_thm_envname_tl` from the active `\l__keythms_thm_parent_tl` reset list, but we want to remove it from the previously set reset list.

However I do agree it would be better to redefine `\__keythms_thm_new_parent:nnn` to set `g__keythms_thm_#1_parent_tl` than having to keep track of where it needs to be set.

**Comment by mbertucci47** [comment]
However I agree it makes sense to just incorporate the definition of the global tl into `\__keythms_thm_new_parent:nnn`. That's done in the most recent commit

**Comment by texno3** [comment]
> However I agree it makes sense to just incorporate the definition of the global tl into `\__keythms_thm_new_parent:nnn`. That's done in the most recent commit

Ok, [`\g__keythms_thm_#1_parent_tl`] is a good idea to distinguish between different theorem bindings counters.(https://github.com/mbertucci47/keytheorems/blob/6ab8907f028f75ed7af75815cc44f19ff3c300dd/tex/keytheorems.sty#L807C1-L807C55)

**Comment by texno3** [comment]
There is still a slight problem with `\newcounter{#1}` creating a counter by adding a counter to the system virtual counter list `\cl@@ckpt`, that is `\@addtoreset{#1}{@ckpt}`, which is used to write the counter situation to the log file `aux` of files that `\include` command inserts.

Looking at `\cl@@ckpt` in the following example reveals two `\@elt {theorem}`, and `\@elt {keythms_restate_dummyctr}\@elt{keythms_continues_dummyctr}\@elt {keythms_unnumbered_dummyctr}`, which are needed to remove duplicates of `\@removefromreset{theorem}{@ckpt}` when redefining the theorem environment, and LaTeX3 syntax does not apply to aux files; internal counters can be named `keythms@restate@dummyctr`.

\documentclass{book}

\usepackage{keytheorems}
\newkeytheorem{theorem}[
name=Theorem, parent=chapter
]
\renewkeytheorem{theorem}[
name=Theorem, parent=section
]

\begin{document}

\makeatletter
\meaning\cl@@ckpt
\makeatother

\end{document}

**Comment by mbertucci47** [comment]
Yes one of the `theorem` entries needs to be removed. I think that applies to any numbered theorem; although now I see if `sibling` is set then aliascnt does not add the aliased counter to this ckpt list.

As for the underscores, I actually think it's okay. For example
```tex
\newcounter{abc_def}
\csname theabc_def\endcsname
```
is fine and as far as I know they are only ever used in `\csname ...\endcsname` constructs. But if you can find an example where they cause an issue I'd be happy to fix.

**Comment by mbertucci47** [comment]
We can't use `\@removefromreset` because it checks if `#2` is a counter but we can just fake it. How does this look?
```tex
\documentclass{book}

\usepackage{keytheorems}

\makeatletter
\def\nocheck@removefromreset#1#2{%
  \begingroup
  \ifcsname c@#2\endcsname
  \else
  \expandafter\def\csname c@#2\endcsname{}%
  \fi
  \@removefromreset{#1}{#2}
  \endgroup
  }
\nocheck@removefromreset{theorem}{@ckpt}
\makeatother

\newkeytheorem{theorem}[
name=Theorem, parent=chapter
]
\renewkeytheorem{theorem}[
name=Theorem, parent=section
]

\begin{document}


\makeatletter
\meaning\cl@@ckpt
\makeatother

\end{document}
```

**Comment by mbertucci47** [comment]
Handled in 2f5591ce182776a1bac393d117d52b3e3083dd69

**Comment by texno3** [comment]
> Handled in [2f5591c](https://github.com/mbertucci47/keytheorems/commit/2f5591ce182776a1bac393d117d52b3e3083dd69)
Okay, but \c@@ckpt must be defined so I don't think that's necessary

**Comment by mbertucci47** [comment]
@texno3 It is not. Try `\meaning\c@@ckpt`

**Comment by mbertucci47** [comment]
Added in [v0.1.6](https://github.com/mbertucci47/keytheorems/releases/tag/v0.1.6) and sent to CTAN
